CREATE TABLE IF NOT EXISTS users (
    user_id         TEXT PRIMARY KEY,
    email           TEXT UNIQUE NOT NULL,
    password_hash   TEXT NOT NULL,
    created_at      TIMESTAMPTZ DEFAULT now(),
    session_version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sessions (
    session_id           TEXT PRIMARY KEY,
    user_id              TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    content_hash         TEXT NOT NULL,
    total_stages         INTEGER NOT NULL DEFAULT 0,
    current_stage_id     INTEGER DEFAULT 0,
    status               TEXT DEFAULT 'active',
    raw_content_summary  TEXT,
    same_material        INTEGER,
    stages_json          TEXT DEFAULT '[]',
    pending_map_json     TEXT,
    provider_name        TEXT,
    model_name           TEXT,
    question_mode        TEXT DEFAULT 'short_answer',
    title                TEXT,
    source_file_ids_json TEXT DEFAULT '[]',
    sources_json         TEXT DEFAULT '[]',
    target_depth         TEXT,
    created_at           TIMESTAMPTZ DEFAULT now(),
    updated_at           TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);

CREATE TABLE IF NOT EXISTS stage_progress (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id         TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    stage_id           INTEGER NOT NULL,
    status             TEXT DEFAULT 'pending',
    attempts           INTEGER DEFAULT 0,
    best_score         DOUBLE PRECISION DEFAULT 0.0,
    understanding_notes TEXT DEFAULT '{}',
    full_explanation   TEXT DEFAULT '',
    questions_json     TEXT DEFAULT '[]',
    completed_at       TIMESTAMPTZ,
    UNIQUE(session_id, stage_id)
);
CREATE INDEX IF NOT EXISTS idx_stage_progress_session ON stage_progress(session_id);

CREATE TABLE IF NOT EXISTS qa_records (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id    TEXT NOT NULL,
    stage_id      INTEGER NOT NULL,
    question_id   TEXT NOT NULL,
    question_text TEXT NOT NULL,
    question_type TEXT,
    user_answer   TEXT,
    score         DOUBLE PRECISION,
    feedback      TEXT,
    created_at    TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_qa_records_session ON qa_records(session_id, stage_id);

CREATE TABLE IF NOT EXISTS concept_mastery (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             TEXT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    concept_name        TEXT NOT NULL,
    mastery_score       DOUBLE PRECISION DEFAULT 0.0,
    total_exposures     INTEGER DEFAULT 0,
    confusion_patterns  TEXT DEFAULT '[]',
    successful_analogies TEXT DEFAULT '[]',
    last_tested         TIMESTAMPTZ,
    source_signature    TEXT,
    UNIQUE(user_id, source_signature, concept_name)
);
CREATE INDEX IF NOT EXISTS idx_concept_mastery_user ON concept_mastery(user_id);

CREATE TABLE IF NOT EXISTS user_learning_profile (
    user_id              TEXT PRIMARY KEY REFERENCES users(user_id) ON DELETE CASCADE,
    preferred_style      TEXT DEFAULT 'concrete',
    avg_attempts_per_stage DOUBLE PRECISION DEFAULT 1.5,
    strong_domains       TEXT DEFAULT '[]',
    weak_domains         TEXT DEFAULT '[]',
    optimal_stage_length INTEGER DEFAULT 500,
    ui_state_json        TEXT DEFAULT '{}',
    updated_at           TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS source_chunks (
    chunk_id      TEXT NOT NULL,
    session_id    TEXT NOT NULL REFERENCES sessions(session_id) ON DELETE CASCADE,
    order_index   INTEGER NOT NULL,
    text          TEXT NOT NULL,
    section_title TEXT,
    char_start    INTEGER,
    char_end      INTEGER,
    source_id     TEXT,
    source_index  INTEGER,
    source_label  TEXT,
    created_at    TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (session_id, chunk_id)
);
CREATE INDEX IF NOT EXISTS idx_source_chunks_session ON source_chunks(session_id);

CREATE TABLE IF NOT EXISTS decision_records (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id             TEXT NOT NULL,
    stage_id               INTEGER NOT NULL,
    decision               TEXT NOT NULL,
    best_score             DOUBLE PRECISION NOT NULL,
    next_stage_id          INTEGER,
    next_stage_score       DOUBLE PRECISION,
    reason_lines_json      TEXT DEFAULT '[]',
    strategy_snapshot_json TEXT DEFAULT '{}',
    created_at             TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_decision_records_session_id ON decision_records(session_id);

CREATE TABLE IF NOT EXISTS tutor_records (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  TEXT NOT NULL,
    stage_id    INTEGER NOT NULL,
    question    TEXT NOT NULL,
    answer      TEXT NOT NULL,
    in_scope    INTEGER NOT NULL DEFAULT 1,
    scope       TEXT,
    created_at  TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_tutor_records_session ON tutor_records(session_id, stage_id);

CREATE TABLE IF NOT EXISTS inflight_locks (
    key        TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    kind       TEXT NOT NULL,
    started_at DOUBLE PRECISION NOT NULL,
    worker_pid INTEGER,
    meta_json  TEXT
);
CREATE INDEX IF NOT EXISTS idx_inflight_session ON inflight_locks(session_id);

CREATE TABLE IF NOT EXISTS curriculum_checkpoints (
    session_id                TEXT PRIMARY KEY REFERENCES sessions(session_id) ON DELETE CASCADE,
    content_hash              TEXT NOT NULL,
    pipeline_version          TEXT NOT NULL DEFAULT 'v2',
    pipeline_meta_json        TEXT NOT NULL DEFAULT '{}',
    required_outline_json     TEXT,
    regions_json              TEXT,
    completed_region_ids_json TEXT NOT NULL DEFAULT '[]',
    all_candidates_json       TEXT NOT NULL DEFAULT '[]',
    summary_parts_json        TEXT NOT NULL DEFAULT '[]',
    meter_json                TEXT NOT NULL DEFAULT '{}',
    last_region_id            TEXT,
    updated_at                TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_curriculum_ckpt_updated ON curriculum_checkpoints(updated_at);

CREATE TABLE IF NOT EXISTS llm_result_cache (
    cache_key      TEXT PRIMARY KEY,
    scope          TEXT NOT NULL DEFAULT 'curriculum',
    content_hash   TEXT,
    agent_name     TEXT NOT NULL,
    region_id      TEXT,
    prompt_version TEXT NOT NULL,
    model_name     TEXT NOT NULL,
    result_json    TEXT NOT NULL,
    input_tokens   INTEGER DEFAULT 0,
    output_tokens  INTEGER DEFAULT 0,
    hit_count      INTEGER NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ DEFAULT now(),
    last_hit_at    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_llm_cache_content_hash ON llm_result_cache(content_hash);
CREATE INDEX IF NOT EXISTS idx_llm_cache_scope_agent ON llm_result_cache(scope, agent_name);
CREATE INDEX IF NOT EXISTS idx_llm_cache_created ON llm_result_cache(created_at);

CREATE TABLE IF NOT EXISTS email_whitelist (
    email      TEXT PRIMARY KEY,
    role       TEXT NOT NULL DEFAULT 'user' CHECK(role IN ('admin','user')),
    note       TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);
