"""
YouTube cookies for yt-dlp (Netscape file or JSON export from browser extensions).
"""
from __future__ import annotations

import json
import os
from pathlib import Path

_BACKEND_ROOT = Path(__file__).resolve().parent.parent


def backend_root() -> Path:
    return _BACKEND_ROOT


def resolve_cookies_source_path() -> Path | None:
    """Return path to cookies file if configured and exists."""
    raw = os.getenv("YOUTUBE_COOKIES_FILE", "").strip()
    if raw:
        path = Path(raw)
        if not path.is_absolute():
            path = _BACKEND_ROOT / path
        return path if path.is_file() else None

    default = _BACKEND_ROOT / "secrets" / "youtube_cookies.json"
    return default if default.is_file() else None


def _load_cookie_entries(path: Path) -> list[dict]:
    text = path.read_text(encoding="utf-8").strip()
    if not text:
        return []
    data = json.loads(text)
    if isinstance(data, list):
        return [x for x in data if isinstance(x, dict)]
    if isinstance(data, dict):
        inner = data.get("cookies")
        if isinstance(inner, list):
            return [x for x in inner if isinstance(x, dict)]
    raise ValueError(f"不支援的 cookies JSON 格式：{path}")


def json_cookies_to_netscape(cookies: list[dict]) -> str:
    lines = [
        "# Netscape HTTP Cookie File",
        "# https://curl.haxx.se/rfc/cookie_spec.html",
        "# Generated by wittgenstein-learning",
    ]
    for item in cookies:
        domain = (item.get("domain") or "").strip()
        name = item.get("name")
        if not domain or not name:
            continue
        value = item.get("value")
        if value is None:
            value = ""
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        cookie_path = item.get("path") or "/"
        secure = "TRUE" if item.get("secure") else "FALSE"
        if item.get("session"):
            expiration = 0
        else:
            raw_exp = item.get("expirationDate", item.get("expires", 0))
            try:
                expiration = int(float(raw_exp or 0))
            except (TypeError, ValueError):
                expiration = 0
        lines.append(
            f"{domain}\t{include_subdomains}\t{cookie_path}\t{secure}\t{expiration}\t{name}\t{value}"
        )
    return "\n".join(lines) + "\n"


def materialize_ytdlp_cookiefile(work_dir: Path) -> str | None:
    """
    Return a path yt-dlp can pass as cookiefile.
    JSON exports are converted to Netscape format inside work_dir.
    """
    source = resolve_cookies_source_path()
    if source is None:
        return None

    if source.suffix.lower() == ".json":
        entries = _load_cookie_entries(source)
        if not entries:
            return None
        dest = work_dir / "youtube_cookies_netscape.txt"
        dest.write_text(json_cookies_to_netscape(entries), encoding="utf-8")
        return str(dest)

    return str(source.resolve())


def ytdlp_cookie_opts(work_dir: Path) -> dict:
    cookiefile = materialize_ytdlp_cookiefile(work_dir)
    if not cookiefile:
        return {}
    return {"cookiefile": cookiefile}
